# Generated by Django 5.2.7 on 2025-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_orderitem_price_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
    ]
