# Generated by Django 5.2.7 on 2025-10-21 06:44

import res.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Django App', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=res.models.favicon_upload_to)),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
